---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: headRef
        must_include:
          regex: '(\b[A-Z][A-Z0-9]+-\d+\b).+$'
          message: 'Your branch name should include JIRA TICKET ID (i.e ABC-1234-test-branch)'
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: approvals
        min:
          count: 1
          message: 'At least 1 developer should approve PR to merge'
        limit:
          teams: ['@lets-docker/test']
          owners: false # Optional boolean. When true, the file .github/CODEOWNER is read and only owners approval will count
        block:
          changes_requested: true # If true, block all approvals when one of the reviewers gave 'changes_requested' review
          message: 'To merge the PR, you have to complete the Change Requests'
