---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: headRef
        must_include:
           regex: '(^|[-\/])(major|release|minor|feature|patch|issue|hotfix|dependabot\/|whitesource)[-\/](\b[A-Z][A-Z0-9]+-\d+\b).+$'
           message: 'Custom message...'
      - do: description
        must_include:
          regex: \b[A-Z][A-Z0-9]+-\d+\b
          message: All pull requests must include a JIRA ticket on it.
      - do: approvals
        min:
          count: 1
          message: 'At least 1 developer should approve PR to merge'
        limit:
          teams: ['@lets-docker/test']
          owners: false # Optional boolean. When true, the file .github/CODEOWNER is read and only owners approval will count
        block:
          changes_requested: true # If true, block all approvals when one of the reviewers gave 'changes_requested' review
          message: 'To merge the PR, you have to complete the Change Requests'
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: description
        must_include:
          regex: \b[A-Z][A-Z0-9]+-\d+\b
          message: All pull requests must include a JIRA ticket on it.
    fail:
      - do: comment
        payload:
          body: >
            The pull request description must have a JIRA ticket
